## Data Loading and PReprocessing

In [1]:
import os
import pandas as pd                                                                                             
import numpy as np

syn_df = pd.read_csv("../Data/data_raw/Syn.csv", nrows=100000)
udp_df = pd.read_csv("../Data/data_raw/DrDoS_UDP.csv", nrows=100000)
udplag_df = pd.read_csv("../Data/data_raw/UDPLag.csv", nrows=100000)
ddos_ldap = pd.read_csv('../Data/data_raw/DrDoS_LDAP.csv', nrows=100000)
ddos_ntp = pd.read_csv('../Data/data_raw/DrDoS_NTP.csv', nrows=100000)
ddos_mssql = pd.read_csv('../Data/data_raw/DrDoS_MSSQL.csv',nrows=100000)
ddos_netbios = pd.read_csv('../Data/data_raw/DrDoS_NetBIOS.csv',nrows=100000)
ddos_snmp = pd.read_csv('../Data/data_raw/DrDoS_SNMP.csv', nrows=100000)
tftp = pd.read_csv('../Data/data_raw/TFTP.csv', nrows=100000)
portmap = pd.read_csv('../Data/data_raw/Portmap.csv', nrows=100000)
ddos_ssdp = pd.read_csv('../Data/data_raw/DrDoS_SSDP.csv', nrows=100000)
net_bios = pd.read_csv('../Data/data_raw/NetBIOS.csv', nrows=100000)
mon_working = pd.read_csv('../Data/data_raw/Monday-WorkingHours.pcap_ISCX.csv', nrows=100000)
tues_working = pd.read_csv('../Data/data_raw/Tuesday-WorkingHours.pcap_ISCX.csv', nrows=100000)
wed_working = pd.read_csv('../Data/data_raw/Wednesday-workingHours.pcap_ISCX.csv', nrows=100000)
fri_working = pd.read_csv('../Data/data_raw/Friday-WorkingHours-Morning.pcap_ISCX.csv', nrows=100000)

print('Dataset: 1',syn_df.columns)
print('Dataset: 2',udp_df.columns)
print('Dataset: 3',udplag_df.columns)
print('Dataset: 4',ddos_ldap.columns)
print('Dataset: 5', ddos_ntp.columns)
print('Dataset: 6',ddos_ssdp.columns)
print('Dataset: 7',mon_working.columns)
print('Dataset: 8',tues_working.columns)
print('Dataset: 9',wed_working.columns)
print('Dataset: 10', fri_working.columns)
print('Dataset: 11',net_bios.columns)
print('Dataset: 12',ddos_ssdp.columns)
print('Dataset: 13',ddos_netbios.columns)
print('Dataset: 14', ddos_mssql.columns)
print('Dataset: 16',tftp.columns)
print('Dataset: 17',portmap.columns)
print('Dataset: 18',ddos_snmp.columns)

C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:5: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  syn_df = pd.read_csv("../Data/data_raw/Syn.csv", nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:6: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  udp_df = pd.read_csv("../Data/data_raw/DrDoS_UDP.csv", nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:7: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  udplag_df = pd.read_csv("../Data/data_raw/UDPLag.csv", nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:8: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_ldap = pd.read_csv('../Data/data_raw/DrDoS_LDAP.csv', nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:9: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_ntp = pd.read_csv('../Data/data_raw/DrDoS_NTP.csv', nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:10: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_mssql = pd.read_csv('../Data/data_raw/DrDoS_MSSQL.csv',nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:11: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_netbios = pd.read_csv('../Data/data_raw/DrDoS_NetBIOS.csv',nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:12: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_snmp = pd.read_csv('../Data/data_raw/DrDoS_SNMP.csv', nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:13: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  tftp = pd.read_csv('../Data/data_raw/TFTP.csv', nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:14: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  portmap = pd.read_csv('../Data/data_raw/Portmap.csv', nrows=100000)
C:\Users\Yash Sangale\AppData\Local\Temp\ipykernel_15008\2040242980.py:15: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  ddos_ssdp = pd.read_csv('../Data/data_raw/DrDoS_SSDP.csv', nrows=100000)

Dataset: 1 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 2 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 3 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 4 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 5 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 6 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')
Dataset: 7 Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')
Dataset: 8 Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')
Dataset: 9 Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')
Dataset: 10 Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='object')
Dataset: 11 Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',

In [2]:
print(os.getcwd())

c:\Users\Yash Sangale\OneDrive\Documents\Desktop\DDoS Detection System\notebooks

#### Checking each dataset working or not

In [3]:
# dataset 3

udp_df.head(10)

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,101418,172.16.0.5-192.168.50.1-43443-6652-17,172.16.0.5,43443,192.168.50.1,6652,17,2018-12-01 12:36:57.628026,218395,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
1,21564,172.16.0.5-192.168.50.1-54741-9712-17,172.16.0.5,54741,192.168.50.1,9712,17,2018-12-01 12:36:57.628076,108219,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
2,23389,172.16.0.5-192.168.50.1-56589-4680-17,172.16.0.5,56589,192.168.50.1,4680,17,2018-12-01 12:36:57.628164,104579,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
3,48872,172.16.0.5-192.168.50.1-40233-2644-17,172.16.0.5,40233,192.168.50.1,2644,17,2018-12-01 12:36:57.628166,110967,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
4,80354,172.16.0.5-192.168.50.1-33989-16901-17,172.16.0.5,33989,192.168.50.1,16901,17,2018-12-01 12:36:57.628217,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
5,85311,172.16.0.5-192.168.50.1-54768-57581-17,172.16.0.5,54768,192.168.50.1,57581,17,2018-12-01 12:36:57.628219,109952,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
6,55736,172.16.0.5-192.168.50.1-58417-6927-17,172.16.0.5,58417,192.168.50.1,6927,17,2018-12-01 12:36:57.628221,770657,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
7,93075,172.16.0.5-192.168.50.1-58450-9815-17,172.16.0.5,58450,192.168.50.1,9815,17,2018-12-01 12:36:57.628336,212482,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
8,11999,172.16.0.5-192.168.50.1-50402-7375-17,172.16.0.5,50402,192.168.50.1,7375,17,2018-12-01 12:36:57.628580,107419,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
9,91182,172.16.0.5-192.168.50.1-58792-38270-17,172.16.0.5,58792,192.168.50.1,38270,17,2018-12-01 12:36:57.628582,105770,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP

In [4]:
ddos_ssdp.columns = ddos_ssdp.columns.str.strip()
ddos_ntp.columns = ddos_ntp.columns.str.strip()
ddos_ldap.columns = ddos_ldap.columns.str.strip()
mon_working.columns = mon_working.columns.str.strip()
tues_working.columns = tues_working.columns.str.strip()
wed_working.columns = wed_working.columns.str.strip()
fri_working.columns = fri_working.columns.str.strip()
ddos_mssql.columns = ddos_mssql.columns.str.strip()
ddos_netbios.columns = ddos_netbios.columns.str.strip()
ddos_snmp.columns = ddos_snmp.columns.str.strip()
tftp.columns = tftp.columns.str.strip()
ddos_ssdp.columns = ddos_ssdp.columns.str.strip()
portmap.columns = portmap.columns.str.strip()
net_bios.columns = net_bios.columns.str.strip()
udplag_df.columns = udplag_df.columns.str.strip()
udp_df.columns = udp_df.columns.str.strip()

### Merging the Dataset's

In [6]:
data = pd.concat([syn_df,udp_df, udplag_df,ddos_ldap, ddos_ntp, ddos_mssql, ddos_netbios, ddos_snmp, tftp, ddos_ssdp, portmap, net_bios ,mon_working, tues_working, wed_working, fri_working], axis=0 )
data = data.reset_index(drop=True)

for col in syn_df.columns:
    print(f"'{col}'")

syn_df.columns = syn_df.columns.str.strip()
udp_df.columns = udp_df.columns.str.strip()
udplag_df.columns = udplag_df.columns.str.strip()

data.columns = data.columns.str.strip()
data['Label'].value_counts()

# data.head(10)

'Unnamed: 0'
'Flow ID'
'Source IP'
'Source Port'
'Destination IP'
'Destination Port'
'Protocol'
'Timestamp'
'Flow Duration'
'Total Fwd Packets'
'Total Backward Packets'
'Total Length of Fwd Packets'
'Total Length of Bwd Packets'
'Fwd Packet Length Max'
'Fwd Packet Length Min'
'Fwd Packet Length Mean'
'Fwd Packet Length Std'
'Bwd Packet Length Max'
'Bwd Packet Length Min'
'Bwd Packet Length Mean'
'Bwd Packet Length Std'
'Flow Bytes/s'
'Flow Packets/s'
'Flow IAT Mean'
'Flow IAT Std'
'Flow IAT Max'
'Flow IAT Min'
'Fwd IAT Total'
'Fwd IAT Mean'
'Fwd IAT Std'
'Fwd IAT Max'
'Fwd IAT Min'
'Bwd IAT Total'
'Bwd IAT Mean'
'Bwd IAT Std'
'Bwd IAT Max'
'Bwd IAT Min'
'Fwd PSH Flags'
'Bwd PSH Flags'
'Fwd URG Flags'
'Bwd URG Flags'
'Fwd Header Length'
'Bwd Header Length'
'Fwd Packets/s'
'Bwd Packets/s'
'Min Packet Length'
'Max Packet Length'
'Packet Length Mean'
'Packet Length Std'
'Packet Length Variance'
'FIN Flag Count'
'SYN Flag Count'
'RST Flag Count'
'PSH Flag Count'
'ACK Flag Count'
'URG Flag Count'
'CWE Flag Count'
'ECE Flag Count'
'Down/Up Ratio'
'Average Packet Size'
'Avg Fwd Segment Size'
'Avg Bwd Segment Size'
'Fwd Header Length.1'
'Fwd Avg Bytes/Bulk'
'Fwd Avg Packets/Bulk'
'Fwd Avg Bulk Rate'
'Bwd Avg Bytes/Bulk'
'Bwd Avg Packets/Bulk'
'Bwd Avg Bulk Rate'
'Subflow Fwd Packets'
'Subflow Fwd Bytes'
'Subflow Bwd Packets'
'Subflow Bwd Bytes'
'Init_Win_bytes_forward'
'Init_Win_bytes_backward'
'act_data_pkt_fwd'
'min_seg_size_forward'
'Active Mean'
'Active Std'
'Active Max'
'Active Min'
'Idle Mean'
'Idle Std'
'Idle Max'
'Idle Min'
'SimillarHTTP'
'Inbound'
'Label'

Label
BENIGN              379265
NetBIOS              99991
TFTP                 99989
Syn                  99986
DrDoS_LDAP           99970
DrDoS_SNMP           99956
DrDoS_SSDP           99886
DrDoS_NetBIOS        99425
DrDoS_MSSQL          99349
DrDoS_UDP            99096
UDP-lag              95913
Portmap              95273
DrDoS_NTP            87466
DoS Hulk             24364
FTP-Patator           7921
DoS slowloris         5796
DoS Slowhttptest      5499
Bot                    442
WebDDoS                413
Name: count, dtype: int64

### After merging the above datasets the distribution of the label column was analyzed to understand the types of network traffic present in the dataset.
The above are the counts were obtained

### Exp: The Label column represents the type of network traffic captures in the each flow record. each label corresponds to a specific type of network behaviour:
- Bengin -> Normal Network Traffic(non-malicious)
- Syn -> SYN Flood Attack
- DrDoS_UDP -> UDP-Based Distributed Denial of Service Attack
- UDP-Lag -> UDP Lag Attack Pattern
- WebDDoS -> Web based Distributed Denial Of Service Attack

### Observations
- The dataset is dominated by attack traffic, which is expected since each dataset file represents a specific DDoS attack scenario.

- The BENIGN traffic represents normal network activity, but its count is significantly smaller compared to attack samples.

- The presence of multiple attack types helps the model learn different patterns of malicious network behavior.

- This dataset structure enables the development of a machine learning model capable of distinguishing between normal traffic and DDoS attack traffic.

In [ ]:
# Removing the spaces from the features and columns

data.columns = data.columns.str.strip()

# Checking the null values
nullCount = data.isnull().sum()
nullCount[nullCount > 0]

# infiniteCount = np.isfinite(data).sum()
# infiniteCount

# data.describe().T

data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 88 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Unnamed: 0                   1200000 non-null  float64
 1   Flow ID                      1200000 non-null  object
 2   Source IP                    1200000 non-null  object
 3   Source Port                  1200000 non-null  float64
 4   Destination IP               1200000 non-null  object
 5   Destination Port             1600000 non-null  int64
 6   Protocol                     1200000 non-null  float64
 7   Timestamp                    1200000 non-null  object
 8   Flow Duration                1600000 non-null  int64
 9   Total Fwd Packets            1600000 non-null  int64
 10  Total Backward Packets       1600000 non-null  int64
 11  Total Length of Fwd Packets  1600000 non-null  float64
 12  Total Length of Bwd Packets  1600000 non-null  float64
 13  Fwd Packet Length Max        1600000 non-null  float64
 14  Fwd Packet Length Min        1600000 non-null  float64
 15  Fwd Packet Length Mean       1600000 non-null  float64
 16  Fwd Packet Length Std        1600000 non-null  float64
 17  Bwd Packet Length Max        1600000 non-null  float64
 18  Bwd Packet Length Min        1600000 non-null  float64
 19  Bwd Packet Length Mean       1600000 non-null  float64
 20  Bwd Packet Length Std        1600000 non-null  float64
 21  Flow Bytes/s                 1581559 non-null  float64
 22  Flow Packets/s               1600000 non-null  float64
 23  Flow IAT Mean                1600000 non-null  float64
 24  Flow IAT Std                 1600000 non-null  float64
 25  Flow IAT Max                 1600000 non-null  float64
 26  Flow IAT Min                 1600000 non-null  float64
 27  Fwd IAT Total                1600000 non-null  float64
 28  Fwd IAT Mean                 1600000 non-null  float64
 29  Fwd IAT Std                  1600000 non-null  float64
 30  Fwd IAT Max                  1600000 non-null  float64
 31  Fwd IAT Min                  1600000 non-null  float64
 32  Bwd IAT Total                1600000 non-null  float64
 33  Bwd IAT Mean                 1600000 non-null  float64
 34  Bwd IAT Std                  1600000 non-null  float64
 35  Bwd IAT Max                  1600000 non-null  float64
 36  Bwd IAT Min                  1600000 non-null  float64
 37  Fwd PSH Flags                1600000 non-null  int64
 38  Bwd PSH Flags                1600000 non-null  int64
 39  Fwd URG Flags                1600000 non-null  int64
 40  Bwd URG Flags                1600000 non-null  int64
 41  Fwd Header Length            1600000 non-null  int64
 42  Bwd Header Length            1600000 non-null  int64
 43  Fwd Packets/s                1600000 non-null  float64
 44  Bwd Packets/s                1600000 non-null  float64
 45  Min Packet Length            1600000 non-null  float64
 46  Max Packet Length            1600000 non-null  float64
 47  Packet Length Mean           1600000 non-null  float64
 48  Packet Length Std            1600000 non-null  float64
 49  Packet Length Variance       1600000 non-null  float64
 50  FIN Flag Count               1600000 non-null  int64
 51  SYN Flag Count               1600000 non-null  int64
 52  RST Flag Count               1600000 non-null  int64
 53  PSH Flag Count               1600000 non-null  int64
 54  ACK Flag Count               1600000 non-null  int64
 55  URG Flag Count               1600000 non-null  int64
 56  CWE Flag Count               1600000 non-null  int64
 57  ECE Flag Count               1600000 non-null  int64
 58  Down/Up Ratio                1600000 non-null  float64
 59  Average Packet Size          1600000 non-null  float64
 60  Avg Fwd Segment Size         1600000 non-null  float64
 61  Avg Bwd Segment Size         1600000 non-null  float64
 62  Fwd Header Length.1          1600000 non-null  int64
 63  Fwd Avg Bytes/Bulk           1600000 non-null  int64
 64  Fwd Avg Packets/Bulk         1600000 non-null  int64
 65  Fwd Avg Bulk Rate            1600000 non-null  int64
 66  Bwd Avg Bytes/Bulk           1600000 non-null  int64
 67  Bwd Avg Packets/Bulk         1600000 non-null  int64
 68  Bwd Avg Bulk Rate            1600000 non-null  int64
 69  Subflow Fwd Packets          1600000 non-null  int64
 70  Subflow Fwd Bytes            1600000 non-null  int64
 71  Subflow Bwd Packets          1600000 non-null  int64
 72  Subflow Bwd Bytes            1600000 non-null  int64
 73  Init_Win_bytes_forward       1600000 non-null  int64
 74  Init_Win_bytes_backward      1600000 non-null  int64
 75  act_data_pkt_fwd             1600000 non-null  int64
 76  min_seg_size_forward         1600000 non-null  int64
 77  Active Mean                  1600000 non-null  float64
 78  Active Std                   1600000 non-null  float64
 79  Active Max                   1600000 non-null  float64
 80  Active Min                   1600000 non-null  float64
 81  Idle Mean                    1600000 non-null  float64
 82  Idle Std                     1600000 non-null  float64
 83  Idle Max                     1600000 non-null  float64
 84  Idle Min                     1600000 non-null  float64
 85  SimillarHTTP                 1200000 non-null  object
 86  Inbound                      1200000 non-null  float64
 87  Label                        1600000 non-null  object
dtypes: float64(49), int64(33), object(6)
memory usage: 1.0+ GB

c:\Users\Yash Sangale\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Yash Sangale\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,1.200000e+06,1.200000e+06,1.600000e+06,1.200000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,...,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.600000e+06,1.200000e+06
mean,1.133897e+05,2.156309e+04,2.580382e+04,1.455902e+01,8.228775e+06,1.315684e+01,8.800598e+00,2.567900e+03,1.698685e+04,3.861457e+02,...,-2.156531e+07,4.667062e+04,2.643026e+04,8.627478e+04,3.081009e+04,2.971874e+06,3.560332e+05,3.392199e+06,2.649375e+06,9.805442e-01
std,1.331730e+05,2.390172e+04,2.173045e+04,4.574338e+00,2.598815e+07,9.270858e+02,1.220258e+03,1.106556e+04,2.756645e+06,4.999436e+02,...,1.498362e+08,5.462727e+05,3.375274e+05,8.247507e+05,4.818334e+05,1.214429e+07,2.232800e+06,1.300739e+07,1.178339e+07,1.381207e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-1.062719e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.256900e+04,6.830000e+02,1.746000e+03,1.700000e+01,1.000000e+00,2.000000e+00,0.000000e+00,4.800000e+01,0.000000e+00,3.700000e+01,...,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
50%,6.874450e+04,1.015000e+03,2.386200e+04,1.700000e+01,3.000000e+00,2.000000e+00,0.000000e+00,4.580000e+02,0.000000e+00,2.290000e+02,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,1.578310e+05,4.497000e+04,4.576600e+04,1.700000e+01,6.163225e+04,4.000000e+00,0.000000e+00,1.398000e+03,0.000000e+00,4.400000e+02,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
max,7.774060e+05,6.553200e+04,6.553500e+04,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.323378e+06,6.554530e+08,2.482000e+04,...,1.480000e+03,1.070000e+08,7.000000e+07,1.070000e+08,1.070000e+08,1.200000e+08,7.590000e+07,1.200000e+08,1.200000e+08,1.000000e+00

In [ ]:
data.isnull().sum().sum()

3618441

In [ ]:
data.drop(
    columns= [ 
    'Unnamed: 0',
    'Flow ID',
    'Source IP',
    'Destination IP',
    'Timestamp',
    'SimillarHTTP',
    'Inbound',
    'Fwd Header Length.1',
    'Fwd Avg Bytes/Bulk',
    'Fwd Avg Packets/Bulk',
    'Fwd Avg Bulk Rate',
    'Bwd Avg Bytes/Bulk',
    'Bwd Avg Packets/Bulk',
    'Bwd Avg Bulk Rate'],
    axis=1, inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 74 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Source Port                  1200000 non-null  float64
 1   Destination Port             1600000 non-null  int64
 2   Protocol                     1200000 non-null  float64
 3   Flow Duration                1600000 non-null  int64
 4   Total Fwd Packets            1600000 non-null  int64
 5   Total Backward Packets       1600000 non-null  int64
 6   Total Length of Fwd Packets  1600000 non-null  float64
 7   Total Length of Bwd Packets  1600000 non-null  float64
 8   Fwd Packet Length Max        1600000 non-null  float64
 9   Fwd Packet Length Min        1600000 non-null  float64
 10  Fwd Packet Length Mean       1600000 non-null  float64
 11  Fwd Packet Length Std        1600000 non-null  float64
 12  Bwd Packet Length Max        1600000 non-null  float64
 13  Bwd Packet Length Min        1600000 non-null  float64
 14  Bwd Packet Length Mean       1600000 non-null  float64
 15  Bwd Packet Length Std        1600000 non-null  float64
 16  Flow Bytes/s                 1581559 non-null  float64
 17  Flow Packets/s               1600000 non-null  float64
 18  Flow IAT Mean                1600000 non-null  float64
 19  Flow IAT Std                 1600000 non-null  float64
 20  Flow IAT Max                 1600000 non-null  float64
 21  Flow IAT Min                 1600000 non-null  float64
 22  Fwd IAT Total                1600000 non-null  float64
 23  Fwd IAT Mean                 1600000 non-null  float64
 24  Fwd IAT Std                  1600000 non-null  float64
 25  Fwd IAT Max                  1600000 non-null  float64
 26  Fwd IAT Min                  1600000 non-null  float64
 27  Bwd IAT Total                1600000 non-null  float64
 28  Bwd IAT Mean                 1600000 non-null  float64
 29  Bwd IAT Std                  1600000 non-null  float64
 30  Bwd IAT Max                  1600000 non-null  float64
 31  Bwd IAT Min                  1600000 non-null  float64
 32  Fwd PSH Flags                1600000 non-null  int64
 33  Bwd PSH Flags                1600000 non-null  int64
 34  Fwd URG Flags                1600000 non-null  int64
 35  Bwd URG Flags                1600000 non-null  int64
 36  Fwd Header Length            1600000 non-null  int64
 37  Bwd Header Length            1600000 non-null  int64
 38  Fwd Packets/s                1600000 non-null  float64
 39  Bwd Packets/s                1600000 non-null  float64
 40  Min Packet Length            1600000 non-null  float64
 41  Max Packet Length            1600000 non-null  float64
 42  Packet Length Mean           1600000 non-null  float64
 43  Packet Length Std            1600000 non-null  float64
 44  Packet Length Variance       1600000 non-null  float64
 45  FIN Flag Count               1600000 non-null  int64
 46  SYN Flag Count               1600000 non-null  int64
 47  RST Flag Count               1600000 non-null  int64
 48  PSH Flag Count               1600000 non-null  int64
 49  ACK Flag Count               1600000 non-null  int64
 50  URG Flag Count               1600000 non-null  int64
 51  CWE Flag Count               1600000 non-null  int64
 52  ECE Flag Count               1600000 non-null  int64
 53  Down/Up Ratio                1600000 non-null  float64
 54  Average Packet Size          1600000 non-null  float64
 55  Avg Fwd Segment Size         1600000 non-null  float64
 56  Avg Bwd Segment Size         1600000 non-null  float64
 57  Subflow Fwd Packets          1600000 non-null  int64
 58  Subflow Fwd Bytes            1600000 non-null  int64
 59  Subflow Bwd Packets          1600000 non-null  int64
 60  Subflow Bwd Bytes            1600000 non-null  int64
 61  Init_Win_bytes_forward       1600000 non-null  int64
 62  Init_Win_bytes_backward      1600000 non-null  int64
 63  act_data_pkt_fwd             1600000 non-null  int64
 64  min_seg_size_forward         1600000 non-null  int64
 65  Active Mean                  1600000 non-null  float64
 66  Active Std                   1600000 non-null  float64
 67  Active Max                   1600000 non-null  float64
 68  Active Min                   1600000 non-null  float64
 69  Idle Mean                    1600000 non-null  float64
 70  Idle Std                     1600000 non-null  float64
 71  Idle Max                     1600000 non-null  float64
 72  Idle Min                     1600000 non-null  float64
 73  Label                        1600000 non-null  object
dtypes: float64(47), int64(26), object(1)
memory usage: 903.3+ MB

In [ ]:
missinng_cols = data.isna()
missinng_cols

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599995,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1599996,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1599997,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1599998,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1599999,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
print(data.isnull().sum().sum())

818441

### Null & Infinity Value handling

In [ ]:
# --- Handling the Missing Values ---

data['Source Port'] = data['Source Port'].fillna(data['Source Port'].median())
print("Source Port Missing Values: ", data['Source Port'].isnull().sum().sum())

data['Protocol'] = data['Protocol'].fillna(data['Protocol'].median())
print("Protocol Missing Values: ", data['Protocol'].isnull().sum().sum())

# data['Inbound'] = data['Inbound'].fillna(data['Inbound'].median())
# print("Innbound Missing Values: ", data['Inbound'].isnull().sum().sum())

Source Port Missing Values:  0
Protocol Missing Values:  0

In [ ]:
# --- Handling the Infinite Values ---

data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.fillna(data.median(numeric_only=True), inplace=True)

In [ ]:
data.isnull().sum().sum()
print(np.isinf(data.select_dtypes(include=[float, int])).sum().sum())

0

#### Converting the Label values Benign(Normal non-attack state) -> 0 and other attacks -> 1

In [ ]:
data['Label'] = data['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

In [ ]:
data['Label'].value_counts()

Label
1    1220735
0     379265
Name: count, dtype: int64

### Feature Sepration

In [ ]:
X = data.drop('Label', axis=1) # -->> Features 
Y = data['Label'] # -->> Target

print("Shape of X: ", X.shape)
print("Shape of Y: ", Y.shape)

Shape of X:  (1600000, 73)
Shape of Y:  (1600000,)

### Saving the processed data into a csv file

In [ ]:
processed_data = data.to_csv('processed_data.csv', index=False)

NameError: name 'data' is not defined

In [ ]:
processed_data.columns()

NameError: name 'processed_data' is not defined